### ISSUE TITLE
x-axis values

### ISSUE THREAD

**Issue by davidmascharka** [rsokl/liveplot#4]
Iteration number can be pretty unwieldy. It would be nice to have an option to label the x-axis by iteration number, epoch, etc.

**Comment by rsokl** [comment]
Do you have any ideas about how to expose this option? Would it be via `create_plot`?

**Comment by davidmascharka** [comment]
That was my first thought. Something like `ticks='iteration'` with options `'iteration'` and `'epoch'`, potentially.

**Comment by rsokl** [comment]
@davidmascharka what do you think of simply using scientific notation for the x-ticks

![image](https://user-images.githubusercontent.com/29104956/58383672-948c4f00-7fa7-11e9-80d5-dd58a61294cb.png)

I am trying to keep the various settable options to a minimum so that resuming a plot from a pickled plotter-dict isn't terrible.

**Comment by rsokl** [comment]
Scientific notation is nice, I went with that
